use_default_settings: true
server:
  secret_key: "change-this-to-random-string"
  limiter: false
  image_proxy: false
search:
  safe_search: 0
  default_lang: "en"
engines:
  - name: google
    engine: google
    shortcut: g
  - name: bing
    engine: bing
    shortcut: b
